repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
        args: [--unsafe]
        exclude: templates
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.7.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      # - id: terragrunt_fmt
      # - id: terragrunt_validate
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.3.1
    hooks:
      - id: packer_fmt
      # - id: packer_validate
