radarr:
  image:
    repository: ghcr.io/home-operations/radarr
    tag: 6.0.3.10276
  env:
    TZ: Europe/Moscow
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host radarr.home.devmem.ru
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 5Gi
    nfs-downloads:
      enabled: true
      existingClaim: nfs-downloads-pvc
      mountPath: /downloads
  resources:
    requests:
      cpu: 50m
      memory: 768Mi
    limits:
      cpu: '2'
      memory: 1Gi
