oauth2-proxy:
  revisionHistoryLimit: 2
  config:
    existingSecret: oauth2-proxy
  ingress:
    enabled: true
    className: nginx
    path: /oauth2
    hosts:
      - &host oauth2-proxy.auth.devmem.ru
    annotations:
      kubernetes.io/tls-acme: "true"
    tls:
      - hosts:
          - *host
        secretName: null
  extraArgs:
    provider: oidc
    oidc-issuer-url: https://dex.auth.devmem.ru
    scope: openid profile email groups
    email-domain: "*"
    cookie-domain: .devmem.ru
    whitelist-domain: .devmem.ru
    silence-ping-logging: true
    skip-provider-button: true
    reverse-proxy: true
    pass-access-token: true
    pass-authorization-header: true
    pass-user-headers: true
    set-authorization-header: true
    set-xauthrequest: true
  initContainers:
    waitForRedis:
      enabled: false
  sessionStorage:
    type: redis
  redis:
    enabled: true
    fullnameOverride: oauth2-proxy-redis
    auth: false
    replicas: 1
    persistentVolume:
      enabled: false
    redis:
      resources:
        limits:
          ephemeral-storage: 1Gi
          memory: 192Mi
        requests:
          cpu: 10m
          ephemeral-storage: 50Mi
          memory: 64Mi
