apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-sts
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: ext4
reclaimPolicy: Retain
