FROM archlinux:latest

RUN pacman --sync --refresh --noconfirm \
        age \
        ansible \
        argocd \
        git \
        helm \
        jq \
        kubectl \
        kustomize \
        make \
        openssh \
        packer \
        python \
        python-hvac \
        python-jmespath \
        python-kubernetes \
        python-pip \
        python-pre-commit \
        sops \
        sudo \
        terraform \
        vault \
        yq
