consul:
  global:
    name: consul
    image: hashicorp/consul:1.21.5
    # renovate: datasource=docker versioning=docker
    imageK8S: hashicorp/consul-k8s-control-plane:1.8.2
    acls:
      manageSystemACLs: true
    metrics:
      enabled: true
      enableAgentMetrics: true
      disableAgentHostName: true
    argocd:
      enabled: true
  server:
    enabled: true
    replicas: 3
    storage: 1Gi
    storageClass: longhorn-sts
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 256Mi
  ui:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host consul.k8s.devmem.ru
      tls:
        - hosts:
            - *host
          secretName: null
  connectInject:
    enabled: false
  tests:
    enabled: false
prometheus-consul-exporter:
  fullnameOverride: consul-exporter
  image:
    repository: prom/consul-exporter
    tag: v0.13.0
  consulServer: consul-server:8500
  serviceMonitor:
    enabled: true
