---
bin_dir: /usr/local/bin
# renovate: depName=opencontainers/runc
runc_version: v1.3.1
runc_url: https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64
# renovate: depName=containernetworking/plugins
cni_version: v1.8.0
cni_url: https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-linux-amd64-{{ cni_version }}.tgz
cni_bin_dir: /opt/cni/bin
cni_cfg_dir: /etc/cni/net.d
# renovate: depName=containerd/containerd
containerd_version: v2.1.4
containerd_url: https://github.com/containerd/containerd/releases/download/{{ containerd_version }}/containerd-{{ containerd_version[1:] }}-linux-amd64.tar.gz
containerd_cfg_dir: /etc/containerd
containerd_registries_mirrors:
  - prefix: docker.io
    mirrors:
      - host: https://mirror.gcr.io
        capabilities: ["pull", "resolve"]
        skip_verify: false
      - host: https://registry-1.docker.io
        capabilities: ["pull", "resolve"]
        skip_verify: false
containerd_utils_packages:
  - pigz
  - isal
# renovate: depName=kubernetes-sigs/cri-tools
crictl_version: v1.32.0
crictl_url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz
# renovate: depName=containerd/nerdctl
nerdctl_version: v2.1.4
nerdctl_url: https://github.com/containerd/nerdctl/releases/download/{{ nerdctl_version }}/nerdctl-{{ nerdctl_version[1:] }}-linux-amd64.tar.gz
nerdctl_cfg_dir: /etc/nerdctl

kubernetes_version: "{{ inventory__kubernetes_version }}"
kubernetes_repo: https://dl.k8s.io/release/{{ kubernetes_version }}/bin/linux/amd64
kubernetes_bins:
  - "{{ kubernetes_repo }}/kubelet"
  - "{{ kubernetes_repo }}/kubectl"
  - "{{ kubernetes_repo }}/kubeadm"
kubernetes_utils_packages:
  - ebtables
  - conntrack
  - socat

sysctl_entries:
  - { name: net.ipv4.ip_forward, value: "1" }
  - { name: net.bridge.bridge-nf-call-iptables, value: "1" }
  - { name: net.bridge.bridge-nf-call-ip6tables, value: "1" }
  - { name: net.bridge.bridge-nf-call-arptables, value: "1" }
  - { name: fs.inotify.max_user_watches, value: "524288" }
  - { name: fs.inotify.max_user_instances, value: "8192" }
  - { name: vm.max_map_count, value: "262144" }
