# Generated by Terraform

[k8s_controlplane_${cluster_name}]
%{ for node_hostname, node_host in k8s_controlplane ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s_workers_${cluster_name}]
%{ for node_hostname, node_host in k8s_workers ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s_lb_${cluster_name}]
%{ for node_hostname, node_host in k8s_lb ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s_${cluster_name}:children]
k8s_controlplane_${cluster_name}
k8s_workers_${cluster_name}
k8s_lb_${cluster_name}

[k8s_${cluster_name}:vars]
ansible_user=${ansible_user}
