# Generated by Terraform

[k8s_controlplane]
%{ for node_hostname, node_host in k8s_controlplane ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s_workers]
%{ for node_hostname, node_host in k8s_workers ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s_lb]
%{ for node_hostname, node_host in k8s_lb ~}
${node_hostname} ansible_host=${node_host}
%{endfor}
[k8s:children]
k8s_controlplane
k8s_workers
k8s_lb

[k8s:vars]
ansible_user=${ansible_user}
